From openjdk:11-jre
WORKDIR usr/src
ENV MONGO_DATABASE=employeedb
ENV MONGO_PORT=27017
ENV MONGO_HOST=localhost
ADD ./target/employeemongo-0.0.1-SNAPSHOT.jar /usr/src/employeemongo-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "employeemongo-0.0.1-SNAPSHOT.jar"]

