
spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
server:
  port: 8083




## server.port=8082

## spring.data.mongodb.database= mytestnewdb
## spring.data.mongodb.uri=mongodb://localhost:27017/mytestnewdb
